// mock-data.js
export const petsData = [
  {
    id: 1,
    name: "Chó Alaska",
    type: "dog",
    breed: "Alaska",
    age: "3 tháng",
    gender: "Đực",
    price: 1500,
    image: "images/alaska.jpg",
    description: "Alaska thuần chủng, khỏe mạnh, đã tiêm phòng đầy đủ",
    vaccinated: true,
    reviews: {
      rating: 4.7,
      count: 52,
    },
  },
  {
    id: 2,
    name: "Mèo Anh lông ngắn",
    type: "cat",
    breed: "British Shorthair",
    age: "2 tháng",
    gender: "Cái",
    price: 800,
    image: "./images/catBrist.avif",
    description: "Mèo Anh thuần chủng, màu xám xanh, mắt vàng đồng",
    vaccinated: true,
    reviews: {
      rating: 4.5,
      count: 38,
    },
  },
  {
    id: 3,
    name: "Chó Poodle",
    type: "dog",
    breed: "Poodle",
    age: "4 tháng",
    gender: "Cái",
    price: 1000,
    image: "./images/poodle.avif",
    description: "Poodle màu nâu đỏ, thông minh, dễ huấn luyện",
    vaccinated: true,
    reviews: {
      rating: 4.8,
      count: 61,
    },
  },
  {
    id: 4,
    name: "Mèo Ba Tư",
    type: "cat",
    breed: "Persian",
    age: "5 tháng",
    gender: "Đực",
    price: 1200,
    image: "./images/persiancat.avif",
    description: "Mèo Ba Tư mặt tịt, lông dài, màu trắng tuyết",
    vaccinated: false,
    reviews: {
      rating: 4.2,
      count: 24,
    },
  },
  {
    id: 5,
    name: "Chó Corgi",
    type: "dog",
    breed: "Corgi",
    age: "3 tháng",
    gender: "Cái",
    price: 2000,
    image: "./images/corgi.avif",
    description: "Corgi chân ngắn siêu dễ thương",
    vaccinated: true,
    reviews: {
      rating: 4.9,
      count: 79,
    },
  },
  {
    id: 6,
    name: "Mèo Ragdoll",
    type: "cat",
    breed: "Ragdoll",
    age: "4 tháng",
    gender: "Cái",
    price: 1500,
    image: "./images/ragdollcat.jpeg",
    description: "Mèo Ragdoll lông dài, tính cách hiền lành",
    vaccinated: true,
    reviews: {
      rating: 4.6,
      count: 35,
    },
  },
  {
    id: 7,
    name: "Chó Pug",
    type: "dog",
    breed: "Pug",
    age: "2 tháng",
    gender: "Đực",
    price: 850,
    image: "./images/Pug-dog.webp",
    description: "Pug mặt xệ đáng yêu, thân thiện với trẻ em",
    vaccinated: true,
    reviews: {
      rating: 4.3,
      count: 40,
    },
  },
  {
    id: 8,
    name: "Mèo Bengal",
    type: "cat",
    breed: "Bengal",
    age: "5 tháng",
    gender: "Cái",
    price: 1800,
    image: "./images/catbengal.avif",
    description: "Bengal họa tiết da báo, năng động",
    vaccinated: true,
    reviews: {
      rating: 4.4,
      count: 46,
    },
  },
];
